
import React from 'react';
import { ChordData } from '../types';

interface SongbookViewProps {
  chords: ChordData[];
  lyrics: string;
  bpm: number;
  capo: number;
  title?: string;
}

const ChordDiagramSVG = ({ chord }: { chord: ChordData }) => {
  const fingering = chord.fingering || [-1, -1, -1, -1, -1, -1];
  // Calculate base fret (if we are high up the neck)
  const activeFrets = fingering.filter(f => f > 0);
  const baseFret = activeFrets.length > 0 && Math.max(...activeFrets) > 4 ? Math.min(...activeFrets) : 1;

  return (
    <div className="flex flex-col items-center mb-4 break-inside-avoid">
      <div className="font-bold text-lg mb-1">{chord.name}</div>
      <svg width="80" height="90" viewBox="0 0 80 90" className="overflow-visible">
        {/* Base Fret Label if > 1 */}
        {baseFret > 1 && (
            <text x="0" y="20" fontSize="10" fontWeight="bold" fill="#000">{baseFret}fr</text>
        )}

        {/* Nut (Top Line) - Thicker if baseFret is 1 */}
        <line x1="10" y1="20" x2="70" y2="20" stroke="#000" strokeWidth={baseFret === 1 ? 3 : 1} />

        {/* Frets (Horizontal) */}
        {[1, 2, 3, 4, 5].map(i => (
            <line key={i} x1="10" y1={20 + i * 12} x2="70" y2={20 + i * 12} stroke="#000" strokeWidth="1" />
        ))}

        {/* Strings (Vertical) */}
        {[0, 1, 2, 3, 4, 5].map(i => (
            <line key={i} x1={10 + i * 12} y1="20" x2={10 + i * 12} y2="80" stroke="#000" strokeWidth="1" />
        ))}

        {/* Dots & X/O */}
        {fingering.map((fret, stringIdx) => {
            const x = 10 + stringIdx * 12;
            
            if (fret === -1) {
                // Mute (X)
                return <text key={stringIdx} x={x} y="12" fontSize="10" textAnchor="middle" fill="#000">×</text>;
            } 
            if (fret === 0) {
                // Open (O)
                return <text key={stringIdx} x={x} y="12" fontSize="10" textAnchor="middle" fill="#000">○</text>;
            }
            
            // Finger Dot
            const relFret = fret - baseFret + 1;
            const y = 20 + (relFret * 12) - 6; // Center in fret space
            return <circle key={stringIdx} cx={x} cy={y} r="4" fill="#000" />;
        })}
      </svg>
      {chord.fingering && (
          <div className="text-[8px] font-mono mt-1 tracking-widest text-slate-600">
             {chord.fingering.map(f => f === -1 ? 'x' : f).join('')}
          </div>
      )}
    </div>
  );
};

export const SongbookView: React.FC<SongbookViewProps> = ({ chords, lyrics, bpm, capo, title }) => {
  return (
    <div className="hidden print:block bg-white text-black p-8 w-full max-w-[210mm] mx-auto min-h-screen">
        {/* Header */}
        <div className="border-b-2 border-black pb-4 mb-8 flex justify-between items-end">
            <div>
                <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">
                    {title || "Untitled Composition"}
                </h1>
                <p className="text-sm font-mono text-slate-600">Generated by VibeChord Studio</p>
            </div>
            <div className="text-right font-mono text-sm">
                <div className="font-bold border border-black px-2 py-1 mb-1 inline-block rounded">BPM: {bpm}</div>
                <div className="font-bold border border-black px-2 py-1 inline-block rounded ml-2">CAPO: {capo}</div>
                <div className="mt-2 text-xs">{new Date().toLocaleDateString()}</div>
            </div>
        </div>

        {/* Progression Section */}
        <div className="mb-8">
            <h2 className="text-sm font-bold uppercase tracking-widest border-b border-black/20 mb-4 pb-1">Progression & Diagrams</h2>
            <div className="flex flex-wrap gap-8 justify-start">
                {chords.map((chord, i) => (
                    <div key={i} className="flex flex-col items-center">
                        <ChordDiagramSVG chord={chord} />
                        {chord.beats && <span className="text-xs font-bold bg-black text-white px-2 rounded-full mt-1">{chord.beats} beats</span>}
                    </div>
                ))}
            </div>
        </div>

        {/* Lyrics Section */}
        {lyrics && (
            <div>
                <h2 className="text-sm font-bold uppercase tracking-widest border-b border-black/20 mb-4 pb-1">Lyrics & Structure</h2>
                <div className="font-mono text-base whitespace-pre-wrap leading-relaxed columns-1 md:columns-2 gap-8">
                    {lyrics}
                </div>
            </div>
        )}
        
        {/* Footer */}
        <div className="fixed bottom-4 left-0 right-0 text-center text-[10px] text-slate-400 print:bottom-8">
            Created with VibeChord • The AI Guitar Studio
        </div>
    </div>
  );
};
